#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_checkpoint_power(info):
    return [ (index, None)  for (index, state) in info ]

def check_checkpoint_power(item, _no_params, info):
    for index, state in info:
        if index == item:
            if state == "Up":
                return (0, "PowerSuppy %s is %s" % (index, state) )
            if state == "Down":
                return (3, "PowerSuppy %s is %s" % (index, state) )
            else:
                return (3, "PowerSuppy %s is in invalid state" % index )

    return (3, "Sensor not found in SNMP output")

check_info["checkpoint_power"] = {
    "check_function"        : check_checkpoint_power,
    "inventory_function"    : inventory_checkpoint_power,
    "service_description"   : "Powersupply %s",
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.4.1.2620.1.6.7.9.1.1.2"),
    "snmp_info"             : ( ".1.3.6.1.4.1.2620.1.6.7.9.1.1", [
                                    "1", # powerSupplyStatusIndex
                                    "2", # powerSupplyStatusState
                              ]),
}

